### PR TITLE
Morris.js css conflict question.

### PR DESCRIPTION
**Pull request by LeKohrs**
Im having a css conflict between the css Ive created and the morris.js css. The hover properties and the chart itself are separated. The hover is where it's suppose to be but the chart itself is underneath the main flow. 

Ive narrowed it down to the float property on the nav class in _nav.scss. If I take that float property out, the chart and hover info realign, but then the flow is off. 

Ive looked up answers online and they all say its a css issue but no answers. 

Would you like a screen shot of how this looks or should I just come up there?

### CODE REVIEW

**Comment by sumeetjain** [comment]
Screen shot, please.

**Comment by LeKohrs** [comment]
screen shot 2014-10-10 at 11 32 38 am

This is what it looks like with the float property in. The div with float property is on the left with the two list items.

**Comment by sumeetjain** [comment]
Best I can tell, `.nav` should be floated left, and so should `#chart`. Check your CSS.

**Comment by sumeetjain** [comment]
With the CSS I suggested, here's what I see:

screen shot 2014-10-10 at 11 35 21 am

**Comment by LeKohrs** [comment]
oh, yeah. I see. I had chart marked as class in css and the code I copied in was id.

Thanks!

**Pull request closed without merging**
